version: "2"
run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # This check has quite a few false positives where there isn't much value in the package comment.
      - linters:
          - staticcheck
        text: "ST1000: at least one file in a package should have a package comment"
      - linters:
          - revive
        text: "var-naming: don't use leading k in Go names"
  settings:
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
                - "github.com/onsi/ginkgo/v2"
                - "github.com/onsi/gomega"
