run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - errorlint
    - revive
    - gosec
    - prealloc
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck

issues:
  exclude-rules:
    # This check has quite a few false positives where there isn't much value in the package comment.
    - text: "ST1000: at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "var-naming: don't use leading k in Go names"
      linters:
        - revive

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: dot-imports
        arguments: [{"allowedPackages": ["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega"]}]
