apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: limitador-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    app: limitador-operator
spec:
  selector:
    matchLabels:
      app: limitador-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: limitador-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
          env:
            - name: RELATED_IMAGE_LIMITADOR
              value: "quay.io/kuadrant/limitador:latest"
          image: controller:latest
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: metrics
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 200Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
