apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: limitador-operator
  name: limitador-operator-metrics
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app: limitador-operator
status:
  loadBalancer: {}
