name: Schedule nightly build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  release-date:
    name: GetDate
    runs-on: ubuntu-latest
    outputs:
      release_date: ${{ steps.release_date.outputs.release_date }}
    steps:
      - id: release_date
        run: echo "release_date=nightly-$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT
  limitador-latest-digest:
    name: Get the digest sha of the latest docker image
    runs-on: ubuntu-latest
    outputs:
      limitador_digest: ${{ steps.get-digest.outputs.digest }}
    steps:
      - id: get-digest
        name: Get digest of latest limitador image
        run: |
          # Get the manifest digest of the latest tag
          DIGEST=$(docker manifest inspect quay.io/kuadrant/limitador:latest -v | jq -r '.Descriptor.digest')
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT
          echo "Limitador latest digest: ${DIGEST}"
  check-limitador-image:
    needs: limitador-latest-digest
    name: Check limitador image exists
    runs-on: ubuntu-latest
    steps:
      - name: Check image
        uses: cloudposse/github-action-docker-image-exists@0.2.0
        with:
          registry: quay.io
          organization: kuadrant
          repository: limitador
          tag: ${{ needs.limitador-latest-digest.outputs.limitador_digest }}
  workflow-build:
    needs: [release-date, check-limitador-image, limitador-latest-digest]
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      operatorVersion: 0.0.0
      operatorTag: ${{ needs.release-date.outputs.release_date }}
      quayImageExpiry: 1w
      limitadorVersion: ${{ needs.limitador-latest-digest.outputs.limitador_digest }}
