name: Build images for latest

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      operatorVersion: 0.0.0
      operatorTag: latest
      quayImageExpiry: never
      limitadorVersion: latest
