name: Build images for branches

on:
  push:
    branches: ['*']
  workflow_dispatch: {}

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      operatorVersion: 0.0.0
      operatorTag: ${{ github.ref_name }}
      limitadorVersion: latest
      imageTags: ${{ github.ref_name }}
