# Description: This workflow is used to release the Helm chart to the GitHub repository. The chart manifests should be already
# built with the target `helm-build` and the manifests changes already committed to the tag to be released.

name: Release Helm Chart
on:
# TODO: The following commented lines should be used depending on the release strategy
#  release:
#    types:
#      - released
# OR for a full release workflow
#  push:
#    tags:
#        - 'v*.*.*'
  workflow_dispatch:
    inputs:
      operatorVersion:
          description: Operator bundle version
          default: 0.0.0
          type: string

jobs:
  chart_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Package Helm Chart
      run: |
        make helm-package

    - name: Upload package to GitHub Release
      uses: svenstaro/upload-release-action@v2
      id: upload-chart
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: charts/limitador-operator-${{ inputs.operatorVersion }}.tgz
        asset_name: chart-limitador-operator-${{ inputs.operatorVersion }}.tgz
        tag: ${{ github.ref }}
        overwrite: true

    - name: Sync Helm Chart with repository
      run: |
        make helm-sync-package \
          VERSION=${{ inputs.operatorVersion }} \
          HELM_WORKFLOWS_TOKEN=${{ secrets.HELM_WORKFLOWS_TOKEN }} \
          BROWSER_DOWNLOAD_URL=${{ steps.upload-chart.outputs.browser_download_url }}
